[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
noisy-core = { path = "crates/noisy-core" }
noisy-audio = { path = "crates/noisy-audio" }
zstd = "0.14"
cpal = "0.18.1"
clap = { version = "4.6.1", features = ["derive"] }
anyhow = "1"
